name: Benchmark
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.4.0

      - name: Install Go
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17

      - name: Get Go environment
        id: go-env
        run: echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.go-env.outputs.modcache }}
          key: benchmark-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            benchmark-${{ runner.os }}-go-

      # Run all benchmarks.
      - name: Run benchmarks
        run: go test -v -bench . -run ^$ ./... | tee benchmark.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: benchmark-result
          path: benchmark.txt
          if-no-files-found: error
          retention-days: 1
