name: Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  telegram:
    uses: gotd/td/.github/workflows/update-schema.yml@main
    with:
      schema-name: "Telegram"
      make-command: "download_schema"

  encrypted:
    uses: gotd/td/.github/workflows/update-schema.yml@main
    with:
      schema-name: "E2E"
      branch: "feat/update-e2e-schema"
      make-command: "download_e2e_schema"

  tdlib:
    uses: gotd/td/.github/workflows/update-schema.yml@main
    with:
      schema-name: "TDLib"
      branch: "feat/update-tdlib-schema"
      make-command: "download_tdlib_schema"
