name: tip

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '36 9 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cleanup
        run: |
          sudo rm -fr /opt/hostedtoolcache/go /usr/local/go /usr/bin/go /bin/go
      - name: install
        run: |
          curl -o go.tar.gz -L \
            https://github.com/AlekSi/golang-tip/releases/download/tip/master.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go.tar.gz
          sudo ln -s /usr/local/go/bin/* /usr/local/bin/
      - uses: actions/checkout@v2
      - name: test
        run: go test ./...
